# Generated by Django 3.2 on 2023-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosAlmacen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='solicitudesdetalle',
            old_name='especificacionesCompras',
            new_name='observacionesCompras',
        ),
        migrations.AddField(
            model_name='solicitudesdetalle',
            name='adjuntoCompras',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='perfil',
            field=models.CharField(choices=[('C', 'Compras'), ('A', 'Almacen'), ('V', 'Validacion'), ('S', 'Solicitud')], default='S', max_length=1),
        ),
    ]
