# Generated by Django 3.2 on 2023-03-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_auto_20230322_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.CharField(choices=[('C', 'Compras'), ('A', 'Almacen'), ('V', 'Validacion'), ('S', 'Solicitud'), ('G', 'Gerencia')], default='S', max_length=1),
        ),
    ]
