# Generated by Django 3.2 on 2023-03-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_alter_usuarios_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='perfil',
            field=models.CharField(choices=[('C', 'Compras'), ('A', 'Almacen'), ('V', 'Validacion'), ('S', 'Solicitud')], default='S', max_length=1),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_identificacion', models.CharField(max_length=30)),
                ('nom_usuario', models.CharField(max_length=150)),
                ('clave_usuario', models.CharField(max_length=20)),
                ('carg_usuario', models.CharField(max_length=80)),
                ('perfil', models.CharField(choices=[('G', 'Gerencia')], default='S', max_length=1)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssedesCompra7', to='solicitud.sedescompra')),
            ],
        ),
    ]
