# Generated by Django 3.2 on 2023-03-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0005_auto_20230323_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenescompra',
            name='aproboCompraStaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sstaff', to='solicitud.staff'),
        ),
    ]
