# Generated by Django 3.2 on 2023-03-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0006_ordenescompra_aprobocomprastaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenescompra',
            name='aproboCompraStaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sstaff', to='solicitud.staff'),
        ),
    ]
