# Generated by Django 3.2 on 2023-03-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0007_alter_ordenescompra_aprobocomprastaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesdetalle',
            name='tipoAdjuntoCompras',
            field=models.CharField(blank=True, choices=[('CSV', 'Csv'), ('PFF', 'Pdf'), ('TEXTO', 'Texto')], max_length=10, null=True),
        ),
    ]
