# Generated by Django 3.2 on 2023-03-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0008_solicitudesdetalle_tipoadjuntocompras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudesdetalle',
            name='tipoAdjuntoCompras',
        ),
    ]
