# Generated by Django 3.2 on 2023-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0009_remove_solicitudesdetalle_tipoadjuntocompras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesdetalle',
            name='especificacionesAlmacen',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
