# Generated by Django 3.2 on 2023-03-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0010_alter_solicitudesdetalle_especificacionesalmacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesdetalle',
            name='especificacionesTecnicas',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
