# Generated by Django 3.2 on 2023-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0013_alter_articulos_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='articulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
